# Generated by Django 5.0.6 on 2024-06-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_contact', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('company_contact', models.CharField(max_length=120)),
                ('company_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_price', models.CharField(max_length=120)),
                ('product_description', models.TextField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.productcategory')),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.productowner')),
                ('product_shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.shippingcompany')),
            ],
        ),
    ]
