# Generated by Django 5.0.6 on 2024-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productowner',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
