# Generated by Django 5.0.6 on 2024-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0002_productowner_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
