# Generated by Django 5.0.6 on 2024-06-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productowner',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productowner',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productowner',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
